### ISSUE TITLE
WrappedWebSocket is not defined

### ISSUE THREAD

**Issue by jespertheend** [jespertheend/splix#109]
Workaround for now is to set simulated latency to 0 at https://splix.io/flags

**Comment by abhishek276533** [comment]
This can be fixed by defining `WrappedWebSocket` using the `var` keyword and the issue will be fixed.

<img width="578" alt="image" src="https://github.com/jespertheend/splix/assets/62441572/56266238-573f-48c4-8a8f-5095c221f3fa">
