### ISSUE TITLE
Restrict movements while dead

### ISSUE THREAD

**Issue by splixcord** [jespertheend/splix#121]
Only allow a movement that causes the player to jump back, potentially undoing their death

**Comment by jespertheend** [comment]
Can this currently be abused in some way?
Doesn't the `!this.dead` check inside `Player.loop()` prevent the player from moving forward?

**Comment by splixcord** [comment]
> Doesn't the `!this.dead` check inside `Player.loop()` prevent the player from moving forward?

There is `this.#drainMovementQueue()` inside `Player.clientPosUpdateRequested`, allowing to make movements in between loops

**Comment by jespertheend** [comment]
Right, but doesn't the lack of the changing `Player.#nextTileProgress` prevent future positions from being handled?

**Comment by splixcord** [comment]
> Right, but doesn't the lack of the changing `Player.#nextTileProgress` prevent future positions from being handled?

It allows changing direction on the current block and triggering actions which can be abused, as well as a visual bug with the trail becoming partially visible again for a moment.

**Comment by jespertheend** [comment]
@splixcord I opened #126, but I'm not really seeing any functional difference. I wasn't able to reproduce the trail becoming visible. Could you tell me if I missed anything?
