### ISSUE TITLE
The game didn't work

### ISSUE THREAD

**Issue by thinkroot99** [jespertheend/splix#128]
All day on 8 11 2023 I had a very hard time logging into the US West, US East and Europe servers. After 2 or 3 times I was able to log in to get off, as soon as I lost I could not log in to any of the 3 servers/worlds mentioned.

**Comment by jespertheend** [comment]
I was having some issues earlier today as well, but I'm not sure what's causing it.
The US East server logs indicate that the process restarted a whole bunch of times, but it doesn't really show the reason for the restarts.
The US West server contains a lot of messages like these:
```
catched in respondWith: Http: connection closed before message completed
```
I'm not sure whether this is a targeted attack or just someone with a bad connection.

**Comment by jespertheend** [comment]
I think it's pretty stable right now. Are you still having issues @thinkroot99?
