### ISSUE TITLE
game server: Players receive invalid skin ids when more than 11 players join with the same skin

### ISSUE THREAD

**Issue by jespertheend** [jespertheend/splix#28]
Not quite sure yet if I can reproduce it reliably, but so far I ran into this issue twice in a row when opening 12 tabs all with the same skin color. Eventually one of the players started rendering as a black circle with none of their captured tiles being visible.

**Comment by abhishek276533** [comment]
Yes, I'm able to reproduce this bug. It's due to `serverToClientColorId` function for playerId `12` it should send `0` but its sending `255`. Raising PR
