### ISSUE TITLE
game server: Ensure trailVertices don't contain unnecessary vertices

### ISSUE THREAD

**Issue by jespertheend** [jespertheend/splix#33]
In `Player.#drainMovementQueue()` new trail vertices are added regardless of whether the previous vertex was already on the same line or not.
Ideally we should check the current direction of the player, and whether the new vertex aligns with the previous vertex according to the direction of the player.

**Comment by abhishek276533** [comment]
We can fix this by adding `!this.pointIsInTrail(this.#currentPosition)` check before pushing `#currentPosition` into `#trailVertices` in `drainMovementQueue()`

Example:
```js
if (this.isGeneratingTrail && !this.pointIsInTrail(this.#currentPosition)) {
	this.#trailVertices.push(firstItem.desiredPosition.clone());
}
```

**Comment by jespertheend** [comment]
I think checking the current direction is more robust. With `pointIsInTrail` it's not immediately clear why that is done and the implementation of `pointIsInTrail` might change in the future. The documentation of `pointIsInTrail` mentions that the current position of the player is included unless `includeLastSegments` is set to `false`, though judging from the implementation this doesn't always seem to be the case.

Using the current direction would also mean it doesn't have to iterate over each vertex, which would be more performant. Though the difference is probably negligible.

**Comment by jespertheend** [comment]
Seems like the issue is more complicated than I thought. Checking the current direction isn't ideal because it might not match the direction of the last two vertices.
Using `pointIsInTrail` wouldn't work either though, because then it would still be possible to create two vertices that are on the same line but at a different position.

I think the best approach is to make a method that either adds a new vertex, or updates the last vertex if it turns out to be aligned with the last segment. We should throw in an assertion for diagonal segments as well, because there seem to be some cases where these are still getting added.
